/**
 * NSE instrument lists used to populate the ticker dropdown.
 * Symbols match Zerodha/Kite Connect tradingsymbols exactly.
 */

export const INDICES = [
  { value: 'NIFTY 50',         label: 'NIFTY 50' },
  { value: 'NIFTY NEXT 50',    label: 'NIFTY NEXT 50' },
  { value: 'NIFTY 100',        label: 'NIFTY 100' },
  { value: 'NIFTY 200',        label: 'NIFTY 200' },
  { value: 'NIFTY 500',        label: 'NIFTY 500' },
  { value: 'NIFTY MIDCAP 50',  label: 'NIFTY MIDCAP 50' },
  { value: 'NIFTY MIDCAP 100', label: 'NIFTY MIDCAP 100' },
  { value: 'NIFTY MIDCAP 150', label: 'NIFTY MIDCAP 150' },
  { value: 'NIFTY SMLCAP 50',  label: 'NIFTY SMALLCAP 50' },
  { value: 'NIFTY SMLCAP 100', label: 'NIFTY SMALLCAP 100' },
  { value: 'NIFTY BANK',       label: 'NIFTY BANK' },
  { value: 'NIFTY IT',         label: 'NIFTY IT' },
  { value: 'NIFTY PHARMA',     label: 'NIFTY PHARMA' },
  { value: 'NIFTY AUTO',       label: 'NIFTY AUTO' },
  { value: 'NIFTY FMCG',       label: 'NIFTY FMCG' },
]

export const NIFTY50_STOCKS = [
  { value: 'ADANIENT',    label: 'ADANIENT — Adani Enterprises' },
  { value: 'ADANIPORTS',  label: 'ADANIPORTS — Adani Ports' },
  { value: 'APOLLOHOSP',  label: 'APOLLOHOSP — Apollo Hospitals' },
  { value: 'ASIANPAINT',  label: 'ASIANPAINT — Asian Paints' },
  { value: 'AXISBANK',    label: 'AXISBANK — Axis Bank' },
  { value: 'BAJAJ-AUTO',  label: 'BAJAJ-AUTO — Bajaj Auto' },
  { value: 'BAJAJFINSV',  label: 'BAJAJFINSV — Bajaj Finserv' },
  { value: 'BAJFINANCE',  label: 'BAJFINANCE — Bajaj Finance' },
  { value: 'BEL',         label: 'BEL — Bharat Electronics' },
  { value: 'BHARTIARTL',  label: 'BHARTIARTL — Bharti Airtel' },
  { value: 'BPCL',        label: 'BPCL — Bharat Petroleum' },
  { value: 'BRITANNIA',   label: 'BRITANNIA — Britannia' },
  { value: 'CIPLA',       label: 'CIPLA — Cipla' },
  { value: 'COALINDIA',   label: 'COALINDIA — Coal India' },
  { value: 'DIVISLAB',    label: 'DIVISLAB — Divi\'s Laboratories' },
  { value: 'DRREDDY',     label: 'DRREDDY — Dr. Reddy\'s' },
  { value: 'EICHERMOT',   label: 'EICHERMOT — Eicher Motors' },
  { value: 'GRASIM',      label: 'GRASIM — Grasim Industries' },
  { value: 'HCLTECH',     label: 'HCLTECH — HCL Technologies' },
  { value: 'HDFCBANK',    label: 'HDFCBANK — HDFC Bank' },
  { value: 'HDFCLIFE',    label: 'HDFCLIFE — HDFC Life Insurance' },
  { value: 'HEROMOTOCO',  label: 'HEROMOTOCO — Hero MotoCorp' },
  { value: 'HINDALCO',    label: 'HINDALCO — Hindalco Industries' },
  { value: 'HINDUNILVR',  label: 'HINDUNILVR — Hindustan Unilever' },
  { value: 'ICICIBANK',   label: 'ICICIBANK — ICICI Bank' },
  { value: 'INDUSINDBK',  label: 'INDUSINDBK — IndusInd Bank' },
  { value: 'INFY',        label: 'INFY — Infosys' },
  { value: 'ITC',         label: 'ITC — ITC' },
  { value: 'JSWSTEEL',    label: 'JSWSTEEL — JSW Steel' },
  { value: 'KOTAKBANK',   label: 'KOTAKBANK — Kotak Mahindra Bank' },
  { value: 'LT',          label: 'LT — Larsen & Toubro' },
  { value: 'LTIM',        label: 'LTIM — LTIMindtree' },
  { value: 'M&M',         label: 'M&M — Mahindra & Mahindra' },
  { value: 'MARUTI',      label: 'MARUTI — Maruti Suzuki' },
  { value: 'NESTLEIND',   label: 'NESTLEIND — Nestle India' },
  { value: 'NTPC',        label: 'NTPC — NTPC' },
  { value: 'ONGC',        label: 'ONGC — Oil & Natural Gas Corp' },
  { value: 'POWERGRID',   label: 'POWERGRID — Power Grid Corp' },
  { value: 'RELIANCE',    label: 'RELIANCE — Reliance Industries' },
  { value: 'SBILIFE',     label: 'SBILIFE — SBI Life Insurance' },
  { value: 'SBIN',        label: 'SBIN — State Bank of India' },
  { value: 'SHRIRAMFIN',  label: 'SHRIRAMFIN — Shriram Finance' },
  { value: 'SUNPHARMA',   label: 'SUNPHARMA — Sun Pharmaceutical' },
  { value: 'TATACONSUM',  label: 'TATACONSUM — Tata Consumer Products' },
  { value: 'TATAMOTORS',  label: 'TATAMOTORS — Tata Motors' },
  { value: 'TATASTEEL',   label: 'TATASTEEL — Tata Steel' },
  { value: 'TCS',         label: 'TCS — Tata Consultancy Services' },
  { value: 'TECHM',       label: 'TECHM — Tech Mahindra' },
  { value: 'TITAN',       label: 'TITAN — Titan Company' },
  { value: 'TRENT',       label: 'TRENT — Trent' },
  { value: 'ULTRACEMCO',  label: 'ULTRACEMCO — UltraTech Cement' },
  { value: 'WIPRO',       label: 'WIPRO — Wipro' },
  { value: 'ZOMATO',      label: 'ZOMATO — Zomato' },
]
